### PR TITLE
Replace gzip detection by xphyle xopen function

### PR DESCRIPTION
**Pull request by natir**
[xphyle](https://github.com/jdidion/xphyle) xopen function open raw, gzip, bzip2, bgzip, lzma and zstd format transparently and use the fastest avaible tools to uncompress the file.

### CODE REVIEW

**Comment by dridk** [comment]
thank ! going to check first if it works on windows / mac before merging

**Comment by dridk** [comment]
Just tested on windows. It seems xphyle is a Linux package only ( depend on command line application)
https://github.com/jdidion/xphyle/issues/41 

The package https://pypi.org/project/xopen/ seems doing the same job and is compatible for windows ( success try).

**Comment by dridk** [comment]
I updated github-CLI workflow to make test on windows.  Because this should not have pass the test

**Comment by natir** [comment]
Ok it's done

**Comment by natir** [comment]
Why did you close without merge ?

**Pull request closed without merging**
